config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :members, only: [:show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]

    resources :recipes, only: [:show, :index] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :lists, only: [:new, :create, :show, :index, :edit, :update]
    post '/create_list' => 'lists#create_list'
    get '/ajax_list' => 'lists#ajax_list'

    resources :members, only: [:show, :index] do
      get '/book_marks' => 'book_marks#book_marks'
      collection do
        patch '/withdraw' => 'members#withdraw'
      end
    end

    resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      collection do
        get '/search' => 'recipes#search'
      end
      resource :book_marks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        resource :checks, only: [:create, :destroy]
      end
    end

    resources :genres, only: [:index] do
      get 'search'
    end
    get '/guests/guest_sign_in' => 'guests#new_guest'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:email]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
  
  belongs_to :member
  belongs_to :recipe
  
end

app/models/check.rb
class Check < ApplicationRecord
  
  belongs_to :member
  belongs_to :comment
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :member
  belongs_to :recipe
  has_many :checks, dependent: :destroy

  validates :body, presence: true

  def checked_by?(member)
    checks.where(member_id: member).exists?
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :recipes, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  
end

app/models/list.rb
class List < ApplicationRecord

  has_many :list_storages, dependent: :destroy
  has_many :recipes, through: :list_storages

  # バリデーション
  with_options presence: true do
    validates :name
    validates :supplier
    validates :name_kana, format: { with: /\A[ｧ-ﾝﾞﾟ]+\z/, message: 'は半角ｶﾀｶﾅで入力して下さい'}
    # "numericality"オプション. "allow_blank: true"空欄の場合にはバリデーションをスキップ
    validates :lot, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
    # "only_integer: true"小数点以下の値を受け入れない
    validates :price, numericality: { only_integer: true, allow_blank: true, message: 'は半角の整数値で入力して下さい' }
    validates :kg_price, numericality: { allow_blank: true, message: 'は半角の整数値で入力して下さい' }
  end

end

app/models/list_storage.rb
class ListStorage < ApplicationRecord

  belongs_to :list
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
  validates :list_id, presence: true

  # 原価
  def cost
    quantity * list.kg_price
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :recipes, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

  # バリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\z/i
  # [\w+\-.]+ は英数字、アンダースコア (_)、プラス (+)、ハイフン (-)、ドット (.) のいずれかを少なくとも1文字以上繰り返す
  # @ を含む
  # [a-z\d\-.]+ は英小文字、数字、ハイフン、ドットのいずれかを少なくとも1文字以上繰り返す
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image

  belongs_to :member
  belongs_to :genre
  has_many :book_marks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :list_storages, dependent: :destroy
  has_many :lists, through: :list_storages
  # cocoonの記述(RecipeモデルとListStorageモデルを同時に作成・更新)
  accepts_nested_attributes_for :list_storages, reject_if: :all_blank, allow_destroy: true

  # バリデーション
  validates_associated :list_storages
  with_options presence: true do
    validates :title, length: { maximum: 50, message: 'は50字以内で入力して下さい' }
    validates :body
    validates :share, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def bookmarked_by?(member)
    book_marks.where(member_id: member).exists?
  end

  def self.search(search)
    # searchが空ならRecipe.allを返す（blankは空という意味）
    return Recipe.all if search.blank?
    Recipe.where('title LIKE ?', "%#{search}%")
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to request.referer, notice: 'コメントが削除されました。'
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController

  def index
    @genres = Genre.page(params[:page]).per(10)
    @genre_new = Genre.new
  end

  def create
    @genre_new = Genre.new(genre_params)
    @genre_new.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  
  def top
    @members = Member.page(params[:page]).per(10)
  end
  
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::ApplicationController

  def show
    @member = Member.find(params[:id])
    @recipes = @member.recipes.page(params[:page]).per(10)
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_root_path, notice: "会員ステータスを更新しました"
    else
      render "show"
    end
  end

  private

  def member_params
    params.require(:member).permit(:is_deleted)
  end

end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < Admin::ApplicationController
  
  def index
    @recipes = Recipe.page(params[:page]).per(10)
  end
  
  def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments.page(params[:page]).per(10)
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto m-5">
      <h3>ジャンル名編集</h3>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto m-5 text-center">
      <%= form_with model: @genre, url:admin_genre_path(@genre.id), method: :patch, local: true do |f| %>
      <%= f.text_field :name, autofocus: true %>
      <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto text-center">
      <div class="error"><%= render 'layouts/error', object: @genre %></div>
    </div>
  </div>
  
  <div class="row">
    <div class="mx-auto text-center">
      <div class="back_btn">
        <%= link_to admin_genres_path do %><i class="fas fa-angle-double-left"></i> <span>一覧に戻る</span><% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto m-5">
      <h3>ジャンル一覧・追加</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9 px-sm-0 mx-auto mb-5">
      <%= form_with model: @genre_new, url:admin_genres_path, method: :post, local: true do |f| %>
        <%= f.text_field :name, placeholder: "ジャンル名" %>
        <%= f.submit "新規登録" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9 px-sm-0 mx-auto mb-5">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <td><%= genre.name %></td>
            <td>
              <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

      <%= paginate @genres, theme: 'bootstrap-5' %>

    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 mx-auto m-4">
      <h3><%= @member.name %></h3>
    </div>

    <div class="mx-auto m-4 pr-5" style="display:flex;">
      <%= form_with model: @member, url:admin_member_path(@member.id), method: :patch do |f| %>
        <%= f.label "会員ステータス" %>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会" %>
        <%= f.submit "変更" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9 px-sm-0 mx-auto mb-5">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>投稿日時</th>
            <th>レシピ名</th>
            <th>コメント数</th>
          </tr>
        </thead>
        <% @recipes.each do |recipe| %>
        <tbody>
          <tr>
            <td><%= recipe.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to admin_recipe_path(recipe) do %><%= recipe.title %><% end %></td>
            <td><%= recipe.comments.count %> 件</td>
          </tr>
        </tbody>
        <% end %>
      </table>

      <%= paginate @recipes, theme: 'bootstrap-5' %>

      <div class="back_btn">
        <%= link_to admin_root_path do %><i class="fas fa-angle-double-left"></i> <span>ユーザー一覧に戻る</span><% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto m-5">
      <h3>レシピ一覧</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9 px-sm-0 mx-auto mb-5">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>投稿日時</th>
            <th>レシピ名</th>
            <th>作成者</th>
            <th>コメント数</th>
          </tr>
        </thead>
        <% @recipes.each do |recipe| %>
        <tbody>
          <tr>
            <td><%= recipe.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to admin_recipe_path(recipe) do %><%= recipe.title %><% end %></td>
            <td><%= recipe.member.name %></td>
            <td><%= recipe.comments.count %> 件</td>
          </tr>
        </tbody>
        <% end %>
      </table>

      <%= paginate @recipes, theme: 'bootstrap-5' %>

    </div>
  </div>
</div>

app/views/admin/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto m-5 text-center">
      <h3><%= @recipe.title %></h3>
      <p>作成者<span class="ml-5"><%= @recipe.member.name %></span></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 px-sm-0 mx-auto mb-5">
      <h4 class="text-left">コメント</h4>
      <table class="table table-hover">
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= comment.member.name %></td>
          <td><%= comment.body %></td>
          <td>
            <%= link_to "削除", admin_recipe_comment_path(comment.recipe,comment), method: :delete, style: "color: #DC143C;", class: "btn btn-link", "data-confirm" => "本当に削除しますか？" %>
          </td>
        </tr>
      <% end %>
      </table>

      <%= paginate @comments, theme: 'bootstrap-5' %>

      <div class="back_btn">
        <%= link_to admin_recipes_path do %><i class="fas fa-angle-double-left"></i> <span>レシピ一覧に戻る</span><% end %>
      </div>
    </div>
  </div>
</div>