config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  devise_for :members, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :members, only: [:show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]

    resources :recipes, only: [:show, :index] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :lists, only: [:new, :create, :show, :index, :edit, :update]
    post '/create_list' => 'lists#create_list'
    get '/ajax_list' => 'lists#ajax_list'

    resources :members, only: [:show, :index] do
      get '/book_marks' => 'book_marks#book_marks'
      collection do
        patch '/withdraw' => 'members#withdraw'
      end
    end

    resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      collection do
        get '/search' => 'recipes#search'
      end
      resource :book_marks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy] do
        resource :checks, only: [:create, :destroy]
      end
    end

    resources :genres, only: [:index] do
      get 'search'
    end
    get '/guests/guest_sign_in' => 'guests#new_guest'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:email]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
  
  belongs_to :member
  belongs_to :recipe
  
end

app/models/check.rb
class Check < ApplicationRecord
  
  belongs_to :member
  belongs_to :comment
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :member
  belongs_to :recipe
  has_many :checks, dependent: :destroy

  validates :body, presence: true

  def checked_by?(member)
    checks.where(member_id: member).exists?
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :recipes, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
  
end

app/models/list.rb
class List < ApplicationRecord

  has_many :list_storages, dependent: :destroy
  has_many :recipes, through: :list_storages

  # バリデーション
  with_options presence: true do
    validates :name
    validates :supplier
    validates :name_kana, format: { with: /\A[ｧ-ﾝﾞﾟ]+\z/, message: 'は半角ｶﾀｶﾅで入力して下さい'}
    # "numericality"オプション. "allow_blank: true"空欄の場合にはバリデーションをスキップ
    validates :lot, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
    # "only_integer: true"小数点以下の値を受け入れない
    validates :price, numericality: { only_integer: true, allow_blank: true, message: 'は半角の整数値で入力して下さい' }
    validates :kg_price, numericality: { allow_blank: true, message: 'は半角の整数値で入力して下さい' }
  end

end

app/models/list_storage.rb
class ListStorage < ApplicationRecord

  belongs_to :list
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
  validates :list_id, presence: true

  # 原価
  def cost
    quantity * list.kg_price
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]

  has_many :recipes, dependent: :destroy
  has_many :book_marks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy

  # バリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\z/i
  # [\w+\-.]+ は英数字、アンダースコア (_)、プラス (+)、ハイフン (-)、ドット (.) のいずれかを少なくとも1文字以上繰り返す
  # @ を含む
  # [a-z\d\-.]+ は英小文字、数字、ハイフン、ドットのいずれかを少なくとも1文字以上繰り返す
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image

  belongs_to :member
  belongs_to :genre
  has_many :book_marks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :list_storages, dependent: :destroy
  has_many :lists, through: :list_storages
  # cocoonの記述(RecipeモデルとListStorageモデルを同時に作成・更新)
  accepts_nested_attributes_for :list_storages, reject_if: :all_blank, allow_destroy: true

  # バリデーション
  validates_associated :list_storages
  with_options presence: true do
    validates :title, length: { maximum: 50, message: 'は50字以内で入力して下さい' }
    validates :body
    validates :share, numericality: { allow_blank: true, message: 'は数値で入力して下さい' }
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def bookmarked_by?(member)
    book_marks.where(member_id: member).exists?
  end

  def self.search(search)
    # searchが空ならRecipe.allを返す（blankは空という意味）
    return Recipe.all if search.blank?
    Recipe.where('title LIKE ?', "%#{search}%")
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController

  def index
    @genres = Genre.page(params[:page]).per(10)
    @genre_new = Genre.new
  end

  def create
    @genre_new = Genre.new(genre_params)
    @genre_new.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  
  def top
    @members = Member.page(params[:page]).per(10)
  end
  
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::ApplicationController

  def show
    @member = Member.find(params[:id])
    @recipes = @member.recipes.page(params[:page]).per(10)
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_root_path, notice: "会員ステータスを更新しました"
    else
      render "show"
    end
  end

  private

  def member_params
    params.require(:member).permit(:is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<div style="color: red;">
<% if object.errors.any? %>
  <div style="font-size: 22px;">
    <%= object.errors.count %>件のエラーがあります
  </div>
  <ul style="list-style:none">
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col">
    <div class="flash text-right mt-3">
      <%= flash[:notice] %>
    </div>
  </div>
</div>


<script>
  $(function() {
    setTimeout("$('.flash').fadeOut('slow')", 3500);
  });
</script>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row" style="padding: 10px;">
    <div class="col-4">
      <p>©Cui-Recette</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color:#cc5e58;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><span style="color:#fff; font-family: 'Sacramento', cursive; font-size:35px;">Cui Recette</span></a>
      <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon "></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if member_signed_in? %>
        <!--Memberログイン後のheader-->
          <li><%= link_to "マイページ", member_path(current_member), class: 'nav-link text-white' %></li>
          <li><%= link_to "新規投稿", new_recipe_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "ユーザー", members_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "レシピ", recipes_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "食材リスト", lists_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-link text-white' %></li>
        <% elsif admin_signed_in? %>
        <!--Adminログイン後のheader-->
          <li><%= link_to "ユーザー", admin_root_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "レシピ", admin_recipes_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "ジャンル", admin_genres_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %></li>
        <% else %>
        <!--ログイン前header-->
          <li><%= link_to "About", about_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "新規登録", new_member_registration_path, class: 'nav-link text-white' %></li>
          <li><%= link_to "ログイン", new_member_session_path, class: 'nav-link text-white' %></li>
        <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="row">
  <div class="col">
    <div class="search float-right mt-3">
      <% if member_signed_in? %>
      <!--Memberログイン中のみ表示させる-->
        <%= form_with url: search_recipes_path, local: true, method: :get do |f| %>
        <%= f.text_field :search, class: "placeholder", placeholder: " レシピ名検索", style: "border-radius:25px;" %>
        <button type="submit"><i class="fas fa-search"></i></button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuiRecette</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/40873ce634.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--スライドショーのレイアウトを制御する独自のCSSを読み込み-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
  </head>

  <body data-turbolinks=false>
    <%= render 'layouts/header' %>
    <main class="min-vh-100" style="background:#fbfaf3">
      <div class="container-fluid">
        <%= render 'layouts/search' %>
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>
    </main>

    <footer class="justify-center" style="background-color:#cc5e58;">
      <%= render 'layouts/footer' %>
    </footer>

    <script>
      // Modalで食材を新規投稿するための記述
      // Listモデルの全てのレコードを取得し、それぞれのidとnameの値を取り出す。".to_json"でJSON形式の文字列に変換。
      var lists = <%= raw List.all.map {|list| {value: list.id, text: list.name}}.to_json %>;
    </script>
  </body>
</html>